### ISSUE TITLE
Plugin Empty recording & IDE Internal Error

### ISSUE THREAD

**Issue by leo18945** [csabagabor/Execution-History-Recorder--Intellij-IDEA-Plugin#1]
Hi, 
Thanks for your plugin, it's so good to analyse the source code, I love it.

I have installed plugin, followed manual at https://csabagabor.github.io/Execution-History-Recorder--Intellij-IDEA-Plugin/, included specific classes, but I got Empty recording like this.

![image](https://user-images.githubusercontent.com/8790495/97517379-0acc8680-19d0-11eb-9f72-0fc16a6c410a.png)

Empty recording
Nothing happened in the app which could be recorded

This is my environment
IntelliJ IDEA 2020.2.3 (Ultimate Edition)
Build #IU-202.7660.26, built on October 6, 2020
Runtime version: 11.0.8+10-b944.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
Execution History Recorder 1.11

And I see a `IDE Internal Error`:

![image](https://user-images.githubusercontent.com/8790495/97516833-fb990900-19ce-11eb-9bde-be58579fc71b.png)

`com.sun.tools.attach.AgentLoadException: 0
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:108)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:119)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:147)
	at gabor.history.action.StartHistoryRunnerConsoleAction.lambda$3(StartHistoryRunnerConsoleAction.java:258)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by csabagabor** [comment]
Hello,
Unfortunately this is a nasty error. The plugin uses a Java agent to instrument classes and this agent is loaded at runtime. On some systems it can happen that this won't work (although I tested it on the latest Ubuntu, Mac OS, Windows 10 before releasing my plugin and worked on all of them). As a workaround for now, please use the new Debugger (which comes bundled with the plugin) to start your application (in this way the Java Agent will be loaded at load-time):
![image](https://user-images.githubusercontent.com/37183688/97601347-bdbdd400-1a12-11eb-811f-94c90efff4d8.png)

Also, I've been working on a new plugin which builds on top of this plugin, but will be uploaded as a separate plugin on the Marketplace, which will be available soon. This new version will work in every edge case.

For example a big limitation is that this plugin doesn't work well on large projects(>10k classes). But this will be solved with the new plugin.

**Comment by steve-todorov** [comment]
Hey, any updates on the new plugin? Are you talking about "execution-god-recorder" ?  :)
